//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_COMPUTATIONALCOMPONENT_H
#define RIAPS_FW_COMPUTATIONALCOMPONENT_H

#include "base/ComputationalComponentBase.h"
#include "time_macros.h"

namespace riapsmodbuscreqrepuart {
   namespace components {
      
      class ComputationalComponent : public ComputationalComponentBase {
         
         public:
         
         ComputationalComponent(const py::object *parent_actor,
                                const py::dict actor_spec,
                                const py::dict type_spec,
                                const std::string &name,
                                const std::string &type_name,
                                const py::dict args,
                                const std::string &application_name,
                                const std::string &actor_name);
         
         virtual void OnClock(riaps::ports::PortBase *port);
         
         bool RecvModbusReqPort(modbusuart::messages::ResponseFormat::Reader &message);
         

         virtual ~ComputationalComponent() = default;

         private:
          pid_t PID;
          bool debugMode;
          bool openReq;
          int nb_holdingRegs;
          int nb_inputRegs;
          std::unique_ptr<uint16_t[]> holdingRegs;
          std::unique_ptr<uint16_t[]> inputRegs;

          // time testing
          struct timespec resolution = {0,0};
          struct timespec preobservations = {0,0};
          struct timespec postobservations = {0,0};
          system_timespec result;
      };
   }
}

std::unique_ptr<riapsmodbuscreqrepuart::components::ComputationalComponent>
create_component_py(const py::object *parent_actor,
                    const py::dict actor_spec,
                    const py::dict type_spec,
                    const std::string &name,
                    const std::string &type_name,
                    const py::dict args,
                    const std::string &application_name,
                    const std::string &actor_name);


#endif //RIAPS_FW_COMPUTATIONALCOMPONENT_H
